### ISSUE TITLE
scroll event not rendering

### ISSUE THREAD

**Issue by mrvilla** [Veams/veams-component-slide-fox#1]
the slider-fox content is not visible. 
* the 'render' is not called on the scroll event.

**Comment by andy-gutsche** [comment]
Please add to your app.js:

```
	// Trigger global resize event
	window.onscroll = Veams.helpers.throttle((e) => {
		Veams.Vent.trigger(Veams.EVENTS.scroll, e);
	}, 200);
```

This snippet will be part of app.js in the next release of generator-veam
